TsnEducationSample/Models/TodoItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace TsnEducation2024.Models
{
    //TODOアイテム管理用クラス
    public class TodoItem
    {

        /// <summary>
        /// タイトル
        /// </summary>
        public string Title { get; set; }

        /// <summary>
        /// 説明
        /// </summary>
        public string Description { get; set; }

    }
}

TsnEducationSample/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TsnEducation2024.Models;

namespace TsnEducation2024.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Sample()
        {
            return View();
        }
    }
}

TsnEducationSample/Controllers/ItakuraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TsnEducation2024.Controllers
{
    public class ItakuraController : Controller
    {
        // GET: Itakura
        public ActionResult Index()
        {
            return View();
        }
    }
}

TsnEducationSample/Controllers/KikuchiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TsnEducation2024.Controllers
{
    public class KikuchiController : Controller
    {
        // GET: Kikuchi
        public ActionResult Index()
        {
            return View();
        }
    }
}

TsnEducationSample/Controllers/MinakawaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TsnEducation2024.Controllers
{
    public class MinakawaController : Controller
    {
        // GET: Minakawa
        public ActionResult Index()
        {
            return View();
        }
    }
}

TsnEducationSample/Controllers/ObaraController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TsnEducation2024.Controllers
{
    public class ObaraController : Controller
    {
        // GET: Obara
        public ActionResult Index()
        {
            return View();
        }
    }
}

TsnEducationSample/Controllers/TodoController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Web;
using System.Web.Mvc;
using TsnEducation2024.Models;

namespace TsnEducation2024.Controllers
{
    public class TodoController : Controller
    {
        /// <summary>
        /// TODOリスト画面表示処理
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            //TODOリストの読み込み
            string filePath = @"C:\temp\TsnEducation2024\todoItem.csv";

            List<TodoItem> todoItems = new List<TodoItem>();
            //ファイルを読み込めなかった場合は空のリストを返す
            if (System.IO.File.Exists(filePath))
            {
                //ファイル読み込み
                using (var readFile = new StreamReader(filePath, Encoding.GetEncoding("shift-jis")))
                {
                    while (!readFile.EndOfStream)
                    {
                        //csvファイルなのでカンマ区切りでデータを抽出
                        string[] rowValues = readFile.ReadLine().Split(',');
                        //データ形式が正しくない場合は扱わない
                        if (rowValues.Length != 2)
                        {
                            continue;
                        }
                        //データを画面表示用に加工
                        todoItems.Add(new TodoItem()
                        {
                            Title = rowValues[0],
                            Description = rowValues[1]
                        });
                    }
                }
            }
            //データモデルの作成、引数に設定
            return View(todoItems);
        }

        /// <summary>
        /// TODOリストの保存
        /// </summary>
        /// <returns></returns>
        public ActionResult SaveTodoItems(List<TodoItem> todoItems)
        {
            //TODO情報を保存するファイル
            string filePath = @"C:\temp\TsnEducation2024\todoItem.csv";
            //保存用ファイルの作成
            CreateFile(filePath);
            //アイテムが空の場合は保存先ファイルを空にする
            if (todoItems == null || !todoItems.Any())
            {
                System.IO.File.WriteAllText(filePath, string.Empty);
            }
            else
            {
                //ファイルの書き込み、保存
                //デリートインサート形式で保存(直前の内容をすべて消し、現在の情報を再登録しなおす)
                using (var overWriteFile = new StreamWriter(filePath, false, Encoding.GetEncoding("shift-jis")))
                {
                    StringBuilder sb = new StringBuilder();
                    foreach (var item in todoItems)
                    {
                        sb.AppendLine($"{item.Title},{item.Description}");
                    }

                    overWriteFile.Write(sb.ToString());
                }
            }

            //成功メッセージを作成
            TempData["SuccessMessage"] = "Todoリストを保存しました。";

            //初期表示画面へリダイレクト
            return RedirectToAction("Index");
        }

        /// <summary>
        /// ファイルを作成する
        /// </summary>
        /// <param name="filePath">作成先のパス</param>
        public void CreateFile(string filePath)
        {
            //ファイルがすでに存在する場合は終了
            if (System.IO.File.Exists(filePath))
            {
                return;
            }

            //フォルダーの作成
            string folderPath = Path.GetDirectoryName(filePath);
            if (!Directory.Exists(folderPath))
            {
                Directory.CreateDirectory(folderPath);
            }
            //ファイルの作成
            var file = System.IO.File.Create(filePath);
            file.Close();

        }
    }
}

TsnEducationSample/Controllers/YamadaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TsnEducation2024.Controllers
{
    public class YamadaController : Controller
    {
        // GET: Yamada
        public ActionResult Index()
        {
            return View();
        }
    }
}

TsnEducationSample/Views/Home/Sample.cshtml
@{
    ViewBag.Title = "サンプル";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title</h2>
    <div class="row">
        <h3>① 電卓</h3>
        <form name="dentaku">
            <table class="calcTable">
                <!-- 液晶画面部分 -->
                <tr>
                    <td colspan="4">
                        <input type="text" class="display" name="display" value="" disabled>
                    </td>
                </tr>

                <!-- 上から1段目（7~9＋÷） -->
                <tr>
                    <td><input type="button" class="calcBtn" value="7" onclick="get_calc(this)"></td>
                    <td><input type="button" class="calcBtn" value="8" onclick="get_calc(this)"></td>
                    <td><input type="button" class="calcBtn" value="9" onclick="get_calc(this)"></td>
                    <td><input type="button" value="÷" class="calcBtn operator" name="div_btn" onclick="get_calc(this)"></td>
                </tr>

                <!-- 上から2段目（4~6＋×） -->
                <tr>
                    <td><input type="button" class="calcBtn" value="4" onclick="get_calc(this)"></td>
                    <td><input type="button" class="calcBtn" value="5" onclick="get_calc(this)"></td>
                    <td><input type="button" class="calcBtn" value="6" onclick="get_calc(this)"></td>
                    <td><input type="button" value="×" class="calcBtn operator" name="multi_btn" onclick="get_calc(this)"></td>
                </tr>

                <!-- 上から3段目（1~3＋-） -->
                <tr>
                    <td><input type="button" class="calcBtn" value="1" onclick="get_calc(this)"></td>
                    <td><input type="button" class="calcBtn" value="2" onclick="get_calc(this)"></td>
                    <td><input type="button" class="calcBtn" value="3" onclick="get_calc(this)"></td>
                    <td><input type="button" value="-" class="calcBtn operator" onclick="get_calc(this)"></td>
                </tr>

                <!-- 上から4段目（0/C/=/+) -->
                <tr>
                    <td><input type="button" class="calcBtn" value="0" onclick="get_calc(this)"></td>
                    <td><input type="button" class="calcBtn" value="C" onclick="get_calc(this)"></td>
                    <td><input type="button" value="=" class="calcBtn equal" onclick="get_calc(this)"></td>
                    <td><input type="button" value="+" class="calcBtn operator" onclick="get_calc(this)"></td>
                </tr>

            </table>
        </form>
    </div>
    <div class="row">
        <h3>② JSON形式のオープンデータを活用した書籍検索</h3>
        <form>
            <div class=" d-flex flex-row gap-2 mb-2">
                <div class="form-group">
                    @Html.Label("", "タイトル", new { @for = "bookTitle" })
                    <input type="text" class="form-control" id="bookTitle">
                </div>
                <div class="form-group">
                    @Html.Label("", "著者名", new { @for = "bookAuthor" })
                    <input type="text" class="form-control" id="bookAuthor">
                </div>
            </div>
            <button type="button" class="btn btn-primary mb-3" id="bookSearch">書籍検索</button>
        </form>
        <h4>書籍検索結果(最大10件表示)</h4>
        <div>
            <table class="table table-bordered" id="bookSearchTable">
                <thead>
                    <tr>
                        <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">#</font></font></th>
                        <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">タイトル</font></font></th>
                        <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">著者</font></font></th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td colspan="3" id="defaultFirstRow" style="text-align: center;">検索結果はありません。</td>
                    </tr>
                </tbody>
            </table>
        </div>

    </div>
    <div class="row">
        <h3>③ いい感じのグラフを表示する(ダッシュボード)</h3>
        @Html.ActionLink("ダッシュボードへ", "Index", "DashBoard", new { area = "" }, new { @class = "action-link" })
    </div>
    <div class="row">
        <h3>④ サーバ側の処理(TODOリスト)</h3>
        @Html.ActionLink("TODOリストへ", "Index", "Todo", new { area = "" }, new { @class = "action-link" })
    </div>
</main>
@section scripts{
    <script type="text/javascript">

        //#region 書籍検索
        //送信ボタンがクリックされたときの処理
        $('#bookSearch').click(function (e) {
            e.preventDefault();

            // 入力された情報を取得
            var title = $('#bookTitle').val();
            var author = $('#bookAuthor').val();
            //検索条件未入力の場合は検索終了
            if (!title && !author) {
                alert("検索情報を入力してください");
                return;
            }

            //デフォルト行を取得
            var defaultFirstRow = $('#defaultFirstRow');
            // tbody要素を取得
            var bookSearchTable = $('#bookSearchTable tbody')[0];

            //URLパラメータ文字列を作成
            var urlParams = "";
            if (title) {
                urlParams = `intitle:${title}`;
            }
            if (author) {
                if (title) {
                    urlParams += `+inauthor:${author}`;
                }
                else {
                    urlParams = `inauthor:${author}`;
                }
            }
            // WebAPIのURL
            // 公式docs(https://developers.google.com/books/docs/v1/using?hl=ja)
            // 使い方の参考(https://labo.kon-ruri.co.jp/google-books-apis/#index_id1)
            var url = 'https://www.googleapis.com/books/v1/volumes?q=' + encodeURIComponent(urlParams);

            // WebAPI実行
            $.ajax({
                url: url,
                //url: 'https://api.openbd.jp/v1/get?isbn=978-4-7741-9690-9',
                type: 'GET',
                dataType: 'json',
                success: function (data) {
                    //現在の検索結果を削除
                    var searchResults = $("#bookSearchTable tbody tr :not(:first)");
                    for (let i = 0; i < searchResults.length; i++) {
                        $(searchResults[i]).remove();
                    }
                    //検索して、データある場合
                    if (data.totalItems > 0) {
                        for (let i = 0; i < data.items.length; i++) {
                            // tbody要素に最下行を追加
                            var trElem = bookSearchTable.insertRow(-1);
                            // td要素(セル要素)を追加
                            var numberCellElem = trElem.insertCell(0);
                            var titleCellElem = trElem.insertCell(1);
                            var authorCellElem = trElem.insertCell(2);
                            //#列
                            var numberCell = document.createElement('span');
                            numberCell.className = "bookSearchContents";
                            numberCell.innerHTML = i+ 1;
                            numberCellElem.appendChild(numberCell);
                            //タイトル列
                            var titleCell = document.createElement('span');
                            titleCell.className = "bookSearchContents";
                            titleCell.innerHTML = data.items[i].volumeInfo.title;
                            titleCellElem.appendChild(titleCell);
                            //著者列
                            var authorCell = titleCell.cloneNode(false);
                            //authorsがない場合は著者列は設定しない
                            if (!('authors' in data.items[i].volumeInfo)) {
                                continue;
                            }
                            for (let j = 0; j < data.items[i].volumeInfo.authors.length; j++) {
                                authorCell.innerHTML += data.items[i].volumeInfo.authors[j];
                                authorCellElem.appendChild(authorCell);
                            }

                        }
                        //検索結果ある場合はデフォルト行非表示
                        defaultFirstRow.hide();
                    }
                    else {
                        //検索結果ない場合はデフォルト行表示
                        defaultFirstRow.show();
                    }
                },
                error: function (data) {
                    alert("書籍検索中にエラーが発生しました。");
                }
            });
        });

        //#endregion

        //#region 電卓の処理
        function get_calc(btn) {
            if (btn.value == "=") {
                //末尾が数値ではない場合は計算しない
                if (isNaN(document.dentaku.display.value.slice(-1)) == true) {
                    return;
                }
                //表示されている文字を計算し、計算結果を表示する
                //TODO: evalはXSS等のセキュリティ脆弱性を突く攻撃につながるため余裕あれば別のものにする
                document.dentaku.display.value = eval(document.dentaku.display.value);
            } else if (btn.value == "C") {
                //表示されている文字を空にする
                document.dentaku.display.value = "";
            } else {
                if (btn.value == "×") {
                    //乗算演算子に変換
                    btn.value = "*";
                } else if (btn.value == "÷") {
                    //除算演算子に変換
                    btn.value = "/";
                }
                //表示文字の設定
                document.dentaku.display.value += btn.value;
                //変換した文字を元に戻す
                document.dentaku.multi_btn.value = "×";
                document.dentaku.div_btn.value = "÷";
            }
        }

        //#endregion</script>

    <style>
        .action-link {
            text-decoration: underline;
            padding-left: calc(var(--bs-gutter-x)* 0.5);
            font-size: 1.5rem;
            width: auto;
        }

        .calcTable {
            /* 電卓のサイズ */
            width: 300px;
            height: 400px;
            /* 電卓が浮き出るように影を付ける */
            border: solid 1px #dcdcdca4;
            border-right: solid 4px #dcdcdca4;
            border-bottom: solid 4px #dcdcdca4;
            border-radius: 10px;
            /* インライン要素を中央に配置 */
            text-align: center;
            /* 余白調整 */
            padding: 8px;
            margin: 20px;
        }

        .calcBtn {
            /* ボタンのサイズ */
            width: 70px;
            height: 70px;
            /* ボタンの文字サイズ */
            font-size: x-large;
            /* 数字部分の背景色 */
            background-color: #dcdcdca4;
            /* ボタンの詳細設定 */
            border: none;
            border-radius: 20px;
            /* クリック時の黒枠を消す */
            outline: none;
        }

        /* ディスプレイの詳細設定 */
        .display {
            width: 250px;
            text-align: right; /* 文字を右詰めに */
            /* 見た目の詳細設定 */
            background: #ffffff;
            border-top: solid #dcdcdca4 5px;
            border-bottom: solid #dcdcdca4 5px;
            border-right: solid #b6b6b6 6px;
            border-left: solid #b6b6b6 6px;
            border-radius: 5px;
        }
        /* 演算子の背景色を上書きで設定 */
        .operator {
            background-color: #87cefa;
        }
        /* 記号＝の部分の背景色を上書きで設定 */
        .equal {
            background-color: #b6b6b6;
        }

        /* カーソルを上に乗せた時に色を濃くする */
        .calcBtn:hover {
            background: #747373b9;
        }

        .display:hover {
            background: #ffffff; /* ディスプレイ部分は無効化 */
        }

        .operator:hover {
            background: #339cdd;
        }

        .operator:active {
            background: #2c80b4;
        }

        /*書籍検索結果テーブルの設定*/
        .table-bordered th:first-child {
            width: 10%;
            min-width: 80px;
        }

        .table-bordered td:first-child {
            width: 10%;
            min-width: 80px;
        }
    </style>
}

TsnEducationSample/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - マイ ASP.NET アプリケーション</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark sticky-top">
        <div class="container">
            @Html.ActionLink("SAMPLE WEB APP", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="ナビゲーションの切り替え" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("ホーム", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("サンプル", "Sample", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("皆川ページ", "Index", "Minakawa", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("山田ページ", "Index", "Yamada", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("菊池ページ", "Index", "kikuchi", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("板倉ページ", "index", "Itakura", new { area = "" }, new { @class = "nav-link" })</li>

                    <li>@Html.ActionLink("小原ページ", "Index", "Obara", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - T.S.Networks 教育委員会</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

TsnEducationSample/Views/Todo/Index.cshtml
@model List<TsnEducation2024.Models.TodoItem>
@{
    ViewBag.Title = "Todoリスト";
}
<main aria-labelledby="title">
    <div class="row">
        @if (TempData["SuccessMessage"] != null)
        {
            <div class="alert alert-success alert-fade d-flex flex-row justify-content-between" role="alert">
                <span>
                    @TempData["SuccessMessage"]
                </span>
                <button type="button" class="btn-close" aria-label="Close"></button>
            </div>
        }
        <div class="d-flex flex-row justify-content-between mb-3">
            <h3>MyTodo</h3>
            @Html.ActionLink("サンプル一覧画面へ戻る", "Sample", "Home", new { area = "" }, new { @class = "sample-link" })
        </div>
        <form>
            <div class="d-flex flex-row gap-2">
                <input class="form-control" type="text" id="todoTitle" placeholder="タイトルを入力" />
                <button class="btn btn-primary " type="button" id="todoSubmit">TODO追加</button>
            </div>
        </form>
        <div id="todoListTable">
            @using (Html.BeginForm("SaveTodoItems", "Todo", FormMethod.Post))
            {
                <div style="display:flex; flex-direction:row; justify-content:space-between;">
                    <h4>TODOリスト一覧</h4>
                    <button class=" btn btn-primary mb-2" type="submit" id="saveTodo">保存</button>
                </div>
                <table class="table table-bordered" id="todoTable">
                    <thead>
                        <tr>
                            <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">操作</font></font></th>
                            <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">タイトル</font></font></th>
                            <th scope="col"><font style="vertical-align: inherit;"><font style="vertical-align: inherit;">説明</font></font></th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            @{string style = string.Empty;
                                //TODOアイテムを保存している場合はデフォルト行を非表示
                                if (Model.Any())
                                {
                                    style = "display:none;";
                                }
                                <td colspan="3" id="defaultFirstRow" style="text-align: center; @style">表示する項目がありません。</td>
                            }
                        </tr>
                        <!--データ表示-->
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td class="text-center">
                                    <button class="btn btn-outline-danger" type="button" id="deleteTodoItem">削除</button>
                                </td>
                                <td>
                                    <span class="todoContents">@item.Title</span>
                                </td>
                                <td>
                                    <span class="todoContents">@item.Description</span>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            }
        </div>
    </div>
</main>
@section scripts{
    <script type="text/javascript">

        //#region TODOリストの処理

        // 追加ボタン押下時の処理
        function addTasks(task) {
            //デフォルト行を取得
            var defaultFirstRow = $('#defaultFirstRow');
            //デフォルト表示を非表示にする
            defaultFirstRow.hide();
            // tbody要素を取得
            var todoTableBody = $('#todoTable tbody')[0];
            // tbody要素に最下行を追加
            var trElem = todoTableBody.insertRow(-1);
            // td要素(セル要素)を追加
            var btnCellElem = trElem.insertCell(0);
            var titleCellElem = trElem.insertCell(1);
            var descriptionCellElem = trElem.insertCell(2);
            //削除ボタンの列
            var deleteBtn = document.createElement('button');
            deleteBtn.id = "deleteTodoItem";
            deleteBtn.className = "btn btn-outline-danger";
            deleteBtn.type = "button";
            deleteBtn.innerHTML = "削除";
            btnCellElem.appendChild(deleteBtn);
            btnCellElem.classList.add("text-center");
            //タイトル列
            var titleCell = document.createElement('span');
            titleCell.className = "todoContents";
            titleCell.innerHTML = task;
            titleCellElem.appendChild(titleCell);
            //説明列
            var descriptionCell = titleCell.cloneNode(false);
            descriptionCell.innerHTML = task + "の説明です。";
            descriptionCellElem.appendChild(descriptionCell);
        };

        // 削除ボタン押下時の処理
        function deleteTasks(deleteBtn, todoTableBody, defaultFirstRow) {
            //デフォルト行を取得
            var defaultFirstRow = $('#defaultFirstRow');
            // tbody要素を取得
            var todoTableBody = $('#todoTable tbody')[0];

            var deleteRow = deleteBtn.closest('tr');
            deleteRow.remove();
            //TODOをすべて消した場合はデフォルト行を表示
            if (todoTableBody.rows.length == 1) {
                defaultFirstRow.show();
            }
        };

        //削除ボタンのクリックイベント設定
        $(document).on('click', '#deleteTodoItem', function (e) {
            e.preventDefault();
            deleteTasks(this);
        });

        //TODO追加ボタンのクリックイベント設定
        $('#todoSubmit').click(function (e) {
            //post処理防止
            e.preventDefault();
            //TODO追加処理
            addTasks($('#todoTitle').val());
            //入力テキストを空にする
            $('#todoTitle').val('');
        });


        //保存ボタンクリック処理
        $('#saveTodo').click(function (e) {
            // tbodyのtr要素(TODOアイテム行)を取得
            var todoItems = $('#todoTable tbody tr');
            //行がない場合は終了
            if (todoItems === null) {
                return false;
            }
            var postItemIndex = 0;
            //行ごとのデータをPOSTメソッドで送れるように加工する
            for (let i = 0; i < todoItems.length; i++) {
                var todoValues = $(todoItems[i]).children("td");
                //td要素(セル)が一つしかない行はデフォルト行なので、処理しない
                if (todoValues.length === 1) {
                    continue;
                }
                //タイトルのデータを作成
                var postTitle = $('<input>').attr({
                    type: 'hidden',
                    name: `todoItems[${postItemIndex}].Title`,
                    value: $(todoValues[1]).find('span')[0].innerHTML
                });
                //説明のデータを作成
                var postDescription = $('<input>').attr({
                    type: 'hidden',
                    name: `todoItems[${postItemIndex}].Description`,
                    value: $(todoValues[2]).find('span')[0].innerHTML
                });

                //データを追加する
                todoItems[i].append(postTitle[0]);
                todoItems[i].append(postDescription[0]);
                postItemIndex++;
            }

        });

        //×ボタン押下処理
        $('.btn-close').click(function (e) {
            var closeElem = this.closest('div');
            closeElem.remove();

        });


        //成功メッセージのフェードアウト
        //setTimeout(function () {
        //    var alertMessage = $('.alert-fade');
        //    if (alertMessage.length == 0) {
        //        return;
        //    }
        //    alertMessage.css('opacity', '0');

        //}, 3000);

        //#endregion

    </script>

    <style>
        .sample-link {
            text-decoration: underline;
            padding-left: calc(var(--bs-gutter-x)* 0.5);
            font-size: 1.5rem;
            width: auto;
        }

        #todoListTable {
            width: 100%;
            height: 400px;
            border-radius: 1rem;
            margin-top: 2rem;
        }

        .table-bordered th:first-child {
            width: 10%;
            min-width: 80px;
        }

        .table-bordered td:first-child {
            width: 10%;
            min-width: 80px;
        }

        .todoContents {
            vertical-align: inherit;
        }

        /*        .alert-fade {
                    transition: opacity 3s;
                }
        */
    </style>
}